spring.application.name=Pension

spring.datasource.url=jdbc:postgresql://localhost:5432/rubix
spring.datasource.username=roba.bairakdar
spring.datasource.password=Passw@rd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true